### PR TITLE
fix: check if bridge is registered and retry

### LINKED ISSUE #3: We lost an error and we got another one in return! :)
We lost an error and we got another one in return! :)

```
To reload the app press "r"
To open developer menu press "d"

 BUNDLE  ./index.js 

 LOG  Running "MultiplyModuleExample" with {"rootTag":1,"initialProps":{}}
 ERROR  ReferenceError: Can't find variable: _turboModule 
App@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:109163:31
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:75798:36
MultiplyModuleExample(RootComponent)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:82546:28
 ERROR  Error: Requiring module "../src/index.ts", which threw an exception: ReferenceError: Can't find variable: _turboModule 
App@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:109163:31
RCTView
RCTView
AppContainer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:75798:36
MultiplyModuleExample(RootComponent)@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=com.example.reactnativemultiplymodule:82546:28
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[2], "/Users/timo/Developer/Playground/react-native-turbomodule-tscodegen/src/index").turboModule')

This error is located at:
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MultiplyModuleExample(RootComponent) (at renderApplication.js:60)
 ERROR  TypeError: undefined is not an object (evaluating '_$$_REQUIRE(_dependencyMap[2], "/Users/timo/Developer/Playground/react-native-turbomodule-tscodegen/src/index").turboModule')

This error is located at:
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in Unknown (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in MultiplyModuleExample(RootComponent) (at renderApplication.js:60)

```

Looks like it can't find the turbo module. I haven't modified anything just installed and run

__Originally posted by @TimoGlastra in https://github.com/blu3beri/react-native-turbomodule-tscodegen/issues/1#issuecomment-983978138__

### PR DESCRIPTION
**Pull request by blu3beri**
closes #3 

@TimoGlastra this will fix it not being registered. Seems a biiiiiit hacky but it does not retry it many times after some testing so it should be okay.

Signed-off-by: Berend Sliedrecht <berend@animo.id>

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]
LGTM

**Comment by blu3beri** [comment]
> Do you know why the setBridge method is called too soon? Is it called by react native?

It is called by react native. I think it is not optimized for turbomodules and therefore is not 100% stable. We should keep an eye on the react native updates to see any changes here.

**Comment by TimoGlastra** [comment]
> We should keep an eye on the react native updates to see any changes here.

There is some preview of documentation on how to setup turbo modules: https://deploy-preview-2879--react-native.netlify.app/docs/next/new-architecture-intro. It requires a nightly release of react native though

**Comment by blu3beri** [comment]
> > We should keep an eye on the react native updates to see any changes here.
> 
> 
> 
> There is some preview of documentation on how to setup turbo modules: https://deploy-preview-2879--react-native.netlify.app/docs/next/new-architecture-intro. It requires a nightly release of react native though

Ah alright. When it hits stable I would like to revisit and optimize the registration as much as possible. For now this will do.

**Pull request merged**
